site_name: 3RWW Sewer Atlas Documentation
site_description: Help documentation for the 3 Rivers Wet Weather Atlas products.
site_favicon: img\favicon.ico
pages:
- Overview: index.md
- Documentation:
    - Interface:  help_rsi_ui.md
    - Common Tasks:  help_rsi_tasks.md
- Guides:
    - Discharge Analysis: guide_rsi_trace.md
- Data:
    - Changelog: changelog.md
markdown_extensions:
    - smarty
site_dir:  
    D:\Dropbox (CivicMapper)\Projects\3RWW\projects\docs\atlas_mkdocs_build\
extra_css:
    - extra.css